# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170226_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poke',
            old_name='count',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='poke',
            old_name='user',
            new_name='victim',
        ),
    ]
