# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170226_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='counter',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='poke',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
